// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VisGist
{
    internal sealed partial class Vsix
    {
        public const string Id = "VisGist.2c55aece-cdd1-4bf3-9239-b6f6d199a364";
        public const string Name = "VisGist";
        public const string Description = @"VisGist integrates your GitHub Gists into Visual Studio allowing you to view, edit, delete and create new Gists straight from the UI.";
        public const string Language = "en-US";
        public const string Version = "1.0.1";
        public const string Author = "stigzler";
        public const string Tags = "GitHub, Gists, Code";
    }
}
