// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VisGist
{
    internal sealed partial class Vsix
    {
        public const string Id = "VisGist.2c55aece-cdd1-4bf3-9239-b6f6d199a364";
        public const string Name = "VisGist";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Steve Hall";
        public const string Tags = "";
    }
}
